apiVersion: v1
kind: Secret
metadata: { name: auth-env, namespace: restauranty }
type: Opaque
stringData:
  SECRET: "CHANGE_ME"
  MONGODB_URI: "mongodb://mongo:27017/flor"
  CLOUD_NAME: "CHANGE_ME"
  CLOUD_API_KEY: "CHANGE_ME"
  CLOUD_API_SECRET: "CHANGE_ME"
  PORT: "3001"
