apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restauranty-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:

      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 3001

      - path: /items
        pathType: Prefix
        backend:
          service:
            name: items
            port:
              number: 3003

      - path: /discounts
        pathType: Prefix
        backend:
          service:
            name: discounts
            port:
              number: 3002

      - path: /
        pathType: Prefix
        backend:
          service:
            name: client
            port:
              number: 80