apiVersion: v1
kind: Secret
metadata:
  name: restauranty-secrets
type: Opaque
stringData:
  SECRET: "MySecret1!"
  MONGODB_URI: "mongodb://mongo:27017/restauranty"
  CLOUD_NAME: "your_cloudinary_name"
  CLOUD_API_KEY: "your_cloudinary_api_key"
  CLOUD_API_SECRET: "your_cloudinary_api_secret"