name: Build and Push Images

on:
  push:
    branches:
      - my-version

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login restaurantyacrshishir.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build images
        run: |
           docker build -t restaurantyacrshishir.azurecr.io/auth:latest ./backend/auth
           docker build -t restaurantyacrshishir.azurecr.io/items:latest ./backend/items
           docker build -t restaurantyacrshishir.azurecr.io/discounts:latest ./backend/discounts
           docker build -t restaurantyacrshishir.azurecr.io/client:latest ./client

      - name: Push images
        run: |
          docker push restaurantyacrshishir.azurecr.io/auth:latest
          docker push restaurantyacrshishir.azurecr.io/items:latest
          docker push restaurantyacrshishir.azurecr.io/discounts:latest
          docker push restaurantyacrshishir.azurecr.io/client:latest